"""empty message

Revision ID: d26558eaefef
Revises: 0625c2f94be9
Create Date: 2025-06-30 02:46:44.500088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26558eaefef'
down_revision: Union[str, None] = '0625c2f94be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('styles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'styles')
    # ### end Alembic commands ###
