"""empty message

Revision ID: f0e77d7e1deb
Revises: ee87e51aace2
Create Date: 2025-06-29 21:08:02.197542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e77d7e1deb'
down_revision: Union[str, None] = 'ee87e51aace2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('button_pressed_5', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('button_pressed_10', sa.Boolean(), nullable=True))
    op.drop_column('user', 'button_pressed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('button_pressed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'button_pressed_10')
    op.drop_column('user', 'button_pressed_5')
    # ### end Alembic commands ###
